version: '3.8'

services:
  cronjobs:
    build:
      context: .
      dockerfile: Dockerfile
    image: python:3.12-alpine
    container_name: hospital-cronjobs
    restart: always
    environment:
      DB_HOST: hospital-database
      DB_PORT: 5432
    networks:
      - database_net_storage

networks:
  database_net_storage:
    external: true