version: '3.8'

services:
  cronjobs:
    build:
      context: .
      dockerfile: Dockerfile
    image: python:3.12-alpine
    container_name: hospital-cronjobs
    restart: always
    volumes:
      - type: bind
        source: ./reports
        target: /app/reports
    environment:
      DB_HOST: hospital-database
      DB_PORT: 5432
    networks:
      - net_storage

networks:
  net_storage:
    external: true